dataset_params:
  use: dynamic
  root_dir: dataset
  dynamic:
    # The following path is where images given in the command line arguments are searched fo
    images_dir: /nas/vista-ssd01/users/mehussein/aifi/dataset/dynamic/images

noise_reg_wgts:
  # - 1e3
  # - 5e3 
  # - 1e4 
  # - 5e4 
  # - 1e5 
  # - 5e5 
  # - 1e6 
  # - 5e6 
  - 1e4
  - 25e3 
  - 50e3 
  - 75e3
  - 1e5 
  - 25e4 
  - 50e4 
  - 75e4
  - 1e6 
  - 25e5

projector_params:
  general:
    batch_size: 5
    num_steps: 1000
    w_avg_samples: 10000
    initial_learning_rate: 0.1
    initial_noise_factor: 0.05
    lr_rampdown_length: 0.25
    lr_rampup_length: 0.05
    noise_ramp_length: 0.75
    verbose: True
    use_generator: ffhq_1024
    use_detector: vgg16
  generators:
    ffhq_1024: 
      img_resolution: 1024
      network_pkl: https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/pretrained/ffhq.pkl
      pth: ''
      local_path: ''
  detectors:
    vgg16:
      network_pkl: ''
      pth: https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/pretrained/metrics/vgg16.pt
      local_path: ''

face_verify_params:
  enabled: True
  csv: 'master-report.csv'
  csv_headers:
    - verified
    - distance
    - max_threshold_to_verify
    - model
    - similarity_metric
    - target
    - detector
    - reg_loss_weight
  
  models:
    - VGG-Face
    - Facenet
    # - Facenet512
    # - OpenFace
    - DeepFace
    # - DeepID
    - ArcFace
    # - Dlib
  metrics:
    - cosine
    # - euclidean
    - euclidean_l2
  detectors:
    - mtcnn
    - opencv
    # - ssd
    # - dlib
    - retinaface